version: '2'

services:
  spl-token-indexer:
    build: ../..
    volumes:
      - ~/indexer.data:/app/data:rw
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - ../../.env
      - ./.env
    environment:
      - INDEXER=spl-token
      - TOKEN=XXXXXXXXXXXXX
      - SOLANA_RPC=http://solrpc1.aleph.cloud:7725/
    network_mode: host
