version: '2'

services:
  port-indexer:
    build: ../..
    volumes:
      - ~/indexer.data:/app/data:rw
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - ../../.env
      - ./.env
    environment:
      - INDEXER=spl-lending
      - LENDING_ID=port
      - SOLANA_RPC=http://solrpc1.aleph.cloud:7725/
    network_mode: bridge

  solend-indexer:
    build: ../..
    volumes:
      - ~/indexer.data:/app/data:rw
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - ../../.env
      - ./.env
    environment:
      - INDEXER=spl-lending
      - LENDING_ID=solend
      - SOLANA_RPC=http://solrpc1.aleph.cloud:7725/
    network_mode: bridge

  larix-indexer:
    build: ../..
    volumes:
      - ~/indexer.data:/app/data:rw
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - ../../.env
      - ./.env
    environment:
      - INDEXER=spl-lending
      - LENDING_ID=larix
      - SOLANA_RPC=http://solrpc1.aleph.cloud:7725/
    network_mode: bridge
